server:
  port: 8080

spring:
  datasource:
    username: data_manager
    password: psw
    url: jdbc:postgresql://localhost:8432/data_manager
    driverClassName: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:29092
    topics:
      input-library: DM_CHANGES
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/library-realm/protocol/openid-connect/certs

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: true
    change-log: classpath:./db/changelog/changelog-data-manager-master.yml
